ci:
  autofix_commit_msg: ":rotating_light: auto fix by pre-commit-ci"
  autofix_prs: true
  autoupdate_branch: master
  autoupdate_schedule: monthly
  autoupdate_commit_msg: ":arrow_up: auto update by pre-commit-ci"

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.34.0"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
